// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPjiggx1PXTLN3jJw4tnIuRqTjPTDjGBo',
    appId: '1:1001705598101:web:3b0dc2a2f64799b749ff9c',
    messagingSenderId: '1001705598101',
    projectId: 'diem-d90b8',
    authDomain: 'diem-d90b8.firebaseapp.com',
    storageBucket: 'diem-d90b8.appspot.com',
    measurementId: 'G-7BLF9LSF3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn1GGyypNZG64iUfH9yRKj2JRw0qvcR-E',
    appId: '1:1001705598101:android:6c98fccd7e10d68f49ff9c',
    messagingSenderId: '1001705598101',
    projectId: 'diem-d90b8',
    storageBucket: 'diem-d90b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYYcKMt3x_GLFUVO_2DNw9SpFh_RrBhiA',
    appId: '1:1001705598101:ios:2671166bebe6c68949ff9c',
    messagingSenderId: '1001705598101',
    projectId: 'diem-d90b8',
    storageBucket: 'diem-d90b8.appspot.com',
    androidClientId: '1001705598101-fts0f2ea17p6ivcqsap09je3t14pugrc.apps.googleusercontent.com',
    iosClientId: '1001705598101-nvajdj2p2s8puqfhkl977nd7a148cc8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.diem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYYcKMt3x_GLFUVO_2DNw9SpFh_RrBhiA',
    appId: '1:1001705598101:ios:be8e3d398c9e668d49ff9c',
    messagingSenderId: '1001705598101',
    projectId: 'diem-d90b8',
    storageBucket: 'diem-d90b8.appspot.com',
    androidClientId: '1001705598101-fts0f2ea17p6ivcqsap09je3t14pugrc.apps.googleusercontent.com',
    iosClientId: '1001705598101-kdhg27ad64mnqk932bhth949uv2a99cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.diem.RunnerTests',
  );
}
