// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDYlKnFws7upgsBh3KOzeXNugLJjYe7-M',
    appId: '1:365874656451:web:b50ca25a18dd4382041e76',
    messagingSenderId: '365874656451',
    projectId: 'diem-ded38',
    authDomain: 'diem-ded38.firebaseapp.com',
    storageBucket: 'diem-ded38.appspot.com',
    measurementId: 'G-QFFL7E30NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZDxn_-IoTuE5tB52slNub5_0EOCT8gxQ',
    appId: '1:365874656451:android:8cabb3e1a3c0c6cd041e76',
    messagingSenderId: '365874656451',
    projectId: 'diem-ded38',
    storageBucket: 'diem-ded38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPOiUpO0gfN9be3bKNFz6DuSBDaXAIN-I',
    appId: '1:365874656451:ios:d461db6ca2ca6278041e76',
    messagingSenderId: '365874656451',
    projectId: 'diem-ded38',
    storageBucket: 'diem-ded38.appspot.com',
    iosClientId: '365874656451-nr5864thbmre39k6evlitu3hnj3ti79i.apps.googleusercontent.com',
    iosBundleId: 'com.example.diem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPOiUpO0gfN9be3bKNFz6DuSBDaXAIN-I',
    appId: '1:365874656451:ios:9032d5fd5b017f5e041e76',
    messagingSenderId: '365874656451',
    projectId: 'diem-ded38',
    storageBucket: 'diem-ded38.appspot.com',
    iosClientId: '365874656451-c91pv36e8f45485k8g53ig126atjga4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.diem.RunnerTests',
  );
}
